services:

  appname:
    build: .
    restart: unless-stopped
    networks:
      - appname
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      - "traefik.http.routers.appname.rule=Host(`test.example.com`)"
      - "traefik.http.routers.appname.middlewares=realiprouter@file"
      - "traefik.http.routers.appname.entrypoints=https"
      - "traefik.http.routers.appname.tls=true"

networks:
  appname:
    name: appname
  traefik:
    name: traefik
